### ISSUE TITLE
dropout_fn is assigned but never used

### ISSUE THREAD

**Issue by mabu-github** [bioinf-jku/SNNs#6]
It seems that dropout_fn is never used.

https://github.com/bioinf-jku/SNNs/blob/7843b6fe5cc89c5006c3543edd22e9b492e4450d/figure1/run.py#L31

**Comment by untom** [comment]
Fixed in Commit https://github.com/bioinf-jku/SNNs/commit/451b61168eba36d9238697025d60183fa0668cd6, thanks for pointing this out.
