### ISSUE TITLE
selu.py is not in package utils

### ISSUE THREAD

**Issue by mabu-github** [bioinf-jku/SNNs#7]
The import seems to be wrong. selu.py is not in a utils folder.

https://github.com/bioinf-jku/SNNs/blob/7843b6fe5cc89c5006c3543edd22e9b492e4450d/figure1/run.py#L31

**Comment by untom** [comment]
It's defined [here](https://github.com/bioinf-jku/SNNs/blob/7843b6fe5cc89c5006c3543edd22e9b492e4450d/figure1/utils.py#L23)
