### ISSUE TITLE
Can someone help me with creating the csv from sdf with exactly the same number of features?

### ISSUE THREAD

**Issue by pdcoded** [bioinf-jku/SNNs#9]
So I used skchem pipeline to feature extract meaningful features from the sdf train file mention in the official Tox21 challenge website. But I am not able to get the 801 features that are there in the zip csv file . Can someone help me with that py code. My aim is to experiment with the architucture with SeLU and technique and not get into domain specific feature extraction details.

**Comment by gklambauer** [comment]
Hello pdcoded,
Thanks for your interest in our work. The Tox21 data with pre-calculated features is avaible here: http://bioinf.jku.at/research/DeepTox/tox21.html. There are various types of input features such as physico-chemical descriptors, extended-connectivity fingerprints (ECFP) and other molecular descriptors that are typically used in that research areas. If you want to calculate your own features from SMILES or SDF file, I can recommend the java-based PaDeL software: http://www.yapcwsoft.com/dd/padeldescriptor/, jCompoundMapper (http://jcompoundmapper.sourceforge.net/) or RDKIT in python. 
Send me an email if you need further assistance!
Regards,
Günter

**Comment by pdcoded** [comment]
Thanks a lot for the quick reply . This would help . If I run into issues, I will mail you.

**Comment by pdcoded** [comment]
but what I am seeing is the row index of test mentioned (tox21_10k_challenge_score.sdf) after I convert it to a csv on the official website and row index of x_te_dense (as mentioned in sample code) don't intersect at all ? So I am doubting the actual test file is not there in this zip ?

**Comment by gklambauer** [comment]
Yes, the actual test of the challenge file is in this zip. If you are talking about the identifiers starting with "NCGC..", then there were some inconsistencies in the challenge that you can fix by adding "-01" at the end. Please check the file "compoundData.csv" that should clarify everything.

**Comment by pdcoded** [comment]
Okay it worked after appending "-01" . Thanks again
